- Integrating changes from https://github.com/quinkennedy/Cinder-WebSocketPP/tree/dev - Renamed _WEBSOCKETPP_NOEXCEPT_TOKEN_ to _NOEXCEPT: allows compiling with VS2015 without error C2694 - Added binary write for client: void WebSocketClient::write(void const * msg, size_t len)